---
- name: Install IIS
  hosts: windows
  gather_facts: true
  tasks:
  - name: install IIS Web-Server with sub features and management tools
    win_feature:
       name: "windows"
       state: present
       restart: yes
       include_sub_features: yes
       include_management_tools: yes
